title: Create an NPC from a model
hero_image: images/banner.png
description: Create an NPC from a model
version: 4
listed: false
copyedit: false
last_tested: "2021-11-24"
steps:
  - 
    title: Create an NPC from a model
